# GolangCI-Lint configuration for Go Template
# Professional linting configuration based on best practices
version: 2

run:
  timeout: 5m

linters-settings:
  # goconst finds repeated strings that could be constants
  goconst:
    min-len: 2
    min-occurrences: 2

  # revive is a fast, configurable, extensible linter
  revive:
    rules:
      - name: unused-parameter
        severity: warning
      - name: var-naming
        severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    # Core linters (enabled by default)
    - errcheck        # Check for unchecked errors
    - govet          # Go vet examiner
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Go static analysis
    - unused         # Check for unused constants, variables, functions
    
    # Additional quality linters
    - bodyclose      # Check HTTP response body is closed
    - misspell       # Find spelling mistakes
    - whitespace     # Check for unnecessary whitespace
    - unconvert      # Remove unnecessary type conversions
    - goconst        # Find repeated strings that could be constants
    - revive         # Fast, configurable linter (replacement for golint)
    - asciicheck     # Check for non-ASCII identifiers
    - durationcheck  # Check for two durations multiplied together
    - nilerr         # Find code that returns nil even if error is not nil
    - noctx          # Detect missing context.Context usage
    - gosec          # Security analysis
